/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestSchemaPolicyUnderlyingExposures { 
    /**
     * Include Commercial Auto
     */
    automobileLiability?: any;
    /**
     * Include Employers Liability
     */
    employersLiability?: any;
    /**
     * Line Umbrella Misc Professional Liability Include Misc Professional Liability
     */
    miscellaneousProfessionalLiability?: any;
    /**
     * Line Umbrella Commercial Auto Include Commercial Auto Hired Non Owned
     */
    automobileLiabilityHiredNonOwned?: any;
    /**
     * Include General Liability
     */
    generalLiability?: any;
    /**
     * Line Umbrella Liquor Liability Include Liquor Liability
     */
    liquorLiability?: any;
    /**
     * Line Umbrella Employee Benefit Include Employee Benefit
     */
    employeeBenefit?: any;
    /**
     * Garage Keepers Liability
     */
    condoOrHoaDirectorsAndOfficers?: any;
    /**
     * Line Umbrella Garage Liability Include Garage Liability
     */
    garageLiability?: any;
    /**
     * Line Umbrella Others Include Others
     */
    includeOthers?: any;
}