/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestSchemaPolicyUmbrellaCommercialAuto { 
    /**
     * Combined single limit of liability (minimum $1,000,000)
     */
    liabilityLimit?: any;
    /**
     * Underlying Premium
     */
    underlyingPremium?: any;
    /**
     * Private Passenger Vehicles:
     */
    privatePassengers?: any;
    /**
     * Light Trucks - 0 to 10K lbs:
     */
    lightTrucks?: any;
    /**
     * Medium Trucks - 10K - 20K lbs:
     */
    mediumTrucks?: any;
    /**
     * Heavy Trucks - 20K - 45K lbs:
     */
    heavyTrucks?: any;
    /**
     * Extra Heavy Trucks/Tractors - Over 45K lbs - Short Haul:
     */
    extraHeavyTruckShortHaul?: any;
    /**
     * Extra Heavy Trucks/Tractors - Over 45K lbs - Long Haul:
     */
    extraHeavyTruckLongHaul?: any;
    /**
     * Buses:
     */
    buses?: any;
    anySchoolOrHospitalityOrShuttleBusesOrVansExposures?: any;
    anyLimousinesOrTaxisOrDeliveryOperationsExposures?: any;
}