/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { RequestSchemaPolicyUmbrellaCommercialAuto } from './requestSchemaPolicyUmbrellaCommercialAuto';
import { RequestSchemaPolicyUnderlyingExposures } from './requestSchemaPolicyUnderlyingExposures';


export interface RequestSchemaPolicy { 
    /**
     * Limit Request
     */
    limit: any;
    classCodes?: any;
    underlyingExposures?: RequestSchemaPolicyUnderlyingExposures;
    umbrellaGeneralLiabilities?: any;
    umbrellaCommercialAuto?: RequestSchemaPolicyUmbrellaCommercialAuto;
    umbrellaEmployersLiabilities?: any;
    umbrellaMiscellanousProfessionalLiabilities?: any;
    umbrellaHiredNonOwnedAuto?: any;
    umbrellaLiquorLiabilities?: any;
    umbrellaEmployeeBenefitsLiabilities?: any;
    umbrellaGarageKeepersLiabilities?: any;
    umbrellaGarageLiabilities?: any;
    umbrellaOtherLiabilities?: any;
}