/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResponseSchemaPolicy { 
    /**
     * Quote Number
     */
    quoteNumber?: any;
    /**
     * Policy Output Policy Status Display
     */
    status?: any;
    /**
     * Full-Term Premium
     */
    premium?: any;
}