/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestSchema { 
    /**
     * Select Product
     */
    product?: any;
    searchBy?: any;
    /**
     * Eligibility Input Search Input Value
     */
    searchInput?: any;
}