/**
 * Escape API
 * This sample documentation outlines how each of the endpoint within the api functions. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResponseSchemaResults { 
    /**
     * Class Code 
     */
    classCode?: any;
    /**
     * Description
     */
    description?: any;
    /**
     * Row Hazard Grade Display Caption
     */
    eligibilty?: any;
    /**
     * Eligibility
     */
    hazardGrade?: any;
    /**
     * Exposure Type
     */
    exposureUnit?: any;
    /**
     * Maximum Exposure
     */
    maximumExposure?: any;
}